[package]
name = "win95"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "Windows 95 look-and-feel widgets for egui"

[dependencies]
egui.workspace = true

[dev-dependencies]
egui_kittest.workspace = true

[lints]
workspace = true
